scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 1s
    static_configs:
      - targets: ['otel-collector:9090']
    metric_relabel_configs:
      - action: labeldrop
        regex: '.*exported.*'
      - action: labeldrop
        regex: '.*instance.*'
      - action: labeldrop
        regex: 'job'
